const products = [
  {
    id: 0,
    name: 'Wind Breaker',
    activity: 'Hikking',
    price: 599.0,
    instock: 100,
    description:
      'Stay warm and dry in any weather while also making a sustainable choice with our versatile and stylish jacket. Made with 100% recycled materials, this jacket is designed to keep you comfortable while minimizing environmental impact. Its water-resistant outer layer and soft inner lining provide insulation, while adjustable features and zippered pockets make it perfect for outdoor adventures or running errands in the city.',
    imgSrc: './images/RainyDays_Jacket2.png',
    numberOfUnits: '',
  },
  {
    id: 1,
    name: 'Winter Armor',
    activity: 'Skiing',
    price: 1299.0,
    instock: 50,
    description: 'Fight winter',
    imgSrc: './images/RainyDays_Jacket1.png',
    numberOfUnits: '',
  },
  {
    id: 2,
    name: 'Spring Jogger',
    activity: 'Canoeing',
    price: 499.0,
    instock: 23,
    description: 'Perfect for Spring',
    imgSrc: './images/RainyDays_Jacket3.png',
    numberOfUnits: '',
  },
  {
    id: 3,
    name: 'Mountain Defender',
    activity: 'Camping',
    price: 1199.0,
    instock: 10,
    description: 'A must have for exploring the mountain range!',
    imgSrc: './images/RainyDays_Jacket4.png',
    numberOfUnits: '',
  },
  {
    id: 4,
    name: 'Fall Break',
    activity: 'Exploring',
    price: 999.0,
    instock: 43,
    description: "Staying warm when the weather isn't.",
    imgSrc: './images/RainyDays_Jacket5.png',
    numberOfUnits: '',
  },
];
